name: Update TVC links

on:
  schedule:
    - cron: "0 0 * * *"   # каждый день в полночь
  workflow_dispatch:       # ручной запуск

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run tvc_peers.py
        run: python tvc_peers.py

      - name: Commit and push updated m3u8
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout -B main  # если используешь main
          git add links/tvc/*.m3u8
          git commit -m "Update TVC links" || echo "No changes"
          git push origin main -f
