name: Update TVC links

on:
  schedule:
    - cron: "0 0 * * *"   # раз в сутки в 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python tvc_peers.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add links/tvc/*.m3u8
          git commit -m "Auto-update tvc links" || echo "No changes"
          git push
